// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function ForgetHost(arg1, arg2) {
  return window['go']['main']['App']['ForgetHost'](arg1, arg2);
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function GetInitialPassword() {
  return window['go']['main']['App']['GetInitialPassword']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServerTransfers() {
  return window['go']['main']['App']['GetServerTransfers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ListLocal(arg1) {
  return window['go']['main']['App']['ListLocal'](arg1);
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function LocalIPs() {
  return window['go']['main']['App']['LocalIPs']();
}

export function LocalMkdir(arg1, arg2) {
  return window['go']['main']['App']['LocalMkdir'](arg1, arg2);
}

export function LocalRoots() {
  return window['go']['main']['App']['LocalRoots']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PickKeyFile() {
  return window['go']['main']['App']['PickKeyFile']();
}

export function RemoteDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteDelete'](arg1, arg2, arg3);
}

export function RemoteMkdir(arg1, arg2) {
  return window['go']['main']['App']['RemoteMkdir'](arg1, arg2);
}

export function RemoteRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteRename'](arg1, arg2, arg3);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function SaveService(arg1, arg2) {
  return window['go']['main']['App']['SaveService'](arg1, arg2);
}

export function SaveSite(arg1) {
  return window['go']['main']['App']['SaveSite'](arg1);
}

export function SetUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUser'](arg1, arg2, arg3);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function TrimMemory() {
  return window['go']['main']['App']['TrimMemory']();
}

export function TrustHost(arg1, arg2) {
  return window['go']['main']['App']['TrustHost'](arg1, arg2);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3);
}
