// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearFinished():Promise<Array<main.TransferInfo>>;

export function Connect(arg1:core.ConnectParams):Promise<main.ConnInfo>;

export function DeleteSite(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:Array<main.RemoteItem>,arg3:string):Promise<void>;

export function ForgetHost(arg1:string,arg2:number):Promise<void>;

export function GetInfo():Promise<main.Info>;

export function GetInitialPassword():Promise<string>;

export function GetLogs():Promise<Array<core.LogEntry>>;

export function GetServerTransfers():Promise<core.TransferSnapshot>;

export function GetSettings():Promise<core.Config>;

export function GetSites():Promise<Array<core.Site>>;

export function GetStatus():Promise<Array<core.ServiceStatus>>;

export function GetTransfers():Promise<Array<main.TransferInfo>>;

export function ListLocal(arg1:string):Promise<main.LocalListing>;

export function ListRemote(arg1:string,arg2:string):Promise<Array<core.RemoteEntry>>;

export function LocalIPs():Promise<Array<string>>;

export function LocalMkdir(arg1:string,arg2:string):Promise<void>;

export function LocalRoots():Promise<Array<string>>;

export function PickFiles():Promise<Array<string>>;

export function PickFolder(arg1:string):Promise<string>;

export function PickKeyFile():Promise<string>;

export function RemoteDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RemoteMkdir(arg1:string,arg2:string):Promise<void>;

export function RemoteRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveService(arg1:string,arg2:core.Config):Promise<void>;

export function SaveSite(arg1:core.Site):Promise<void>;

export function SetUser(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function TrimMemory():Promise<boolean>;

export function TrustHost(arg1:string,arg2:main.HostPrompt):Promise<void>;

export function Upload(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;
